version: '3'
services:
  webservice:
    build: ./backend
    volumes:
      - './backend:/app'
    ports:
      - "3001:3001"
    depends_on:
    - mongo
  mongo:
    image: mongo
    ports:
    - "27017:27017"
  website:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - './frontend:/app'
    depends_on:
      - webservice